.\"                                      Hey, EMACS: -*- nroff -*-
.TH DUDLC 1 "2002-08-01"
.SH NAME
dudlc \- command line client for dudld jukebox
.SH SYNOPSIS
.B dudlc
.RI [ options ]
.SH DESCRIPTION
This manual page documents briefly the
.B dudlc
command.
.PP
\fBdudlc\fP is a readline enabled textmode client to access a dudld
jukebox.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
For a complete description, see the Info files.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-H, \-\-host <hostname>
Specify host to connect to.
.TP
.B \-P, \-\-port <port>
dudld port.
.TP
.B \-u, \-\-user <name>
dudld user.
.TP
.B \-p, \-\-pass <pass>
dudld password.
.TP
.B \-c, \-\-command <cmd>
run specified command and exit immediately.

.SH FILES
$HOME/.dudlc.conf

.SH SEE ALSO
.BR dudlc.conf (5),
.BR dudl_cmd (1),
.BR dudl_filter (1),
.BR irdudl (1),
.BR dudld (8).
.br
.SH AUTHOR
This manual page was written by Rainer Clasen.
