.\"                                      Hey, EMACS: -*- nroff -*-
.TH IRDUDL 1 "2002-08-01"
.SH NAME
irdudl \- lirc line client for dudld jukebox
.SH SYNOPSIS
.B irdudl
.RI [ options ]
.B <lirc_config>
.SH DESCRIPTION
This manual page documents briefly the
.B irdudl
command.
.PP
\fBirdudl\fP is a lirc client to access a dudld jukebox.

The specified 
.B <lirc_config>
defines the commands issued on lirc key presses. It uses the same syntax
as irexec. Please consult the lirc documentation for a description.

.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
For a complete description, see the Info files.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-H, \-\-host <hostname>
Specify host to connect to.
.TP
.B \-P, \-\-port <port>
dudld port.
.TP
.B \-u, \-\-user <name>
dudld user.
.TP
.B \-p, \-\-pass <pass>
dudld password.
.TP
.B \-b, \-\-beep
send beep to local console after every command.
.TP
.B \-f, \-\-foreground
do not detach from current terminal and stay in foreground.
.TP
.B \-f, \-\-debug
enable debug logging.
.TP
.B \-l, \-\-pidfile <pidfile>
file to store the pid in. For use in init scripts and to avoid duplicate
instances.

.SH SEE ALSO
.BR dudl_filter (1),
.BR dudlc (1),
.BR dudld (8).
.br
.SH AUTHOR
This manual page was written by Rainer Clasen.
